// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CAlligatorFunction wrapper class

class CAlligatorFunction : public COleDispatchDriver
{
public:
	CAlligatorFunction() {}		// Calls COleDispatchDriver default constructor
	CAlligatorFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAlligatorFunction(const CAlligatorFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetTeethPen();
	CPen1 GetLipsPen();
};
