// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartAnimations;

/////////////////////////////////////////////////////////////////////////////
// CAnimationList wrapper class

class CAnimationList : public COleDispatchDriver
{
public:
	CAnimationList() {}		// Calls COleDispatchDriver default constructor
	CAnimationList(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAnimationList(const CAnimationList& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add(long AnimationClass);
	CChartAnimations GetItems(long Index);
	VARIANT GetControlDefault(long Index);
	void Clear();
	void Delete(long Index);
	long GetCount();
	void SetActive(BOOL bNewValue);
	void Exchange(long Index1, long Index2);
};
