// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAxisBreak wrapper class

class CAxisBreak : public COleDispatchDriver
{
public:
	CAxisBreak() {}		// Calls COleDispatchDriver default constructor
	CAxisBreak(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisBreak(const CAxisBreak& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	double GetEndValue();
	void SetEndValue(double newValue);
	double GetStartValue();
	void SetStartValue(double newValue);
	long GetAxisBreakStyle();
	void SetAxisBreakStyle(long nNewValue);
};
