// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAxisBreaks;
class CPen1;
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CAxisBreaksTool wrapper class

class CAxisBreaksTool : public COleDispatchDriver
{
public:
	CAxisBreaksTool() {}		// Calls COleDispatchDriver default constructor
	CAxisBreaksTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisBreaksTool(const CAxisBreaksTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetAxis();
	void SetAxis(const VARIANT& newValue);
	CAxisBreaks GetBreaks();
	long GetGapSize();
	void SetGapSize(long nNewValue);
	CPen1 GetPen();
	CBrush1 GetBrush();
};
