// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeCustomShape;

/////////////////////////////////////////////////////////////////////////////
// CAxisLabelsItem wrapper class

class CAxisLabelsItem : public COleDispatchDriver
{
public:
	CAxisLabelsItem() {}		// Calls COleDispatchDriver default constructor
	CAxisLabelsItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisLabelsItem(const CAxisLabelsItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetValue();
	void SetValue(double newValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	long GetLabelPos();
	void SetLabelPos(long nNewValue);
	CTeeCustomShape GetFormat();
};
