// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CAxisArrowTool wrapper class

class CAxisArrowTool : public COleDispatchDriver
{
public:
	CAxisArrowTool() {}		// Calls COleDispatchDriver default constructor
	CAxisArrowTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisArrowTool(const CAxisArrowTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetAxis();
	void SetAxis(const VARIANT& newValue);
	long GetPosition();
	void SetPosition(long nNewValue);
	CBrush1 GetBrush();
	long GetLength();
	void SetLength(long nNewValue);
	CPen1 GetPen();
	long GetScrollPercent();
	void SetScrollPercent(long nNewValue);
	BOOL GetScrollInverted();
	void SetScrollInverted(BOOL bNewValue);
	long GetHeadWidth();
	void SetHeadWidth(long nNewValue);
	long GetSizePercent();
	void SetSizePercent(long nNewValue);
};
