// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSubChartChart;
class CSubChart;

/////////////////////////////////////////////////////////////////////////////
// CChartCollection wrapper class

class CChartCollection : public COleDispatchDriver
{
public:
	CChartCollection() {}		// Calls COleDispatchDriver default constructor
	CChartCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartCollection(const CChartCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSubChartChart AddChart(LPCTSTR AName);
	CSubChart GetItems(long Index);
	void Clear();
	void Delete(long AIndex);
	long GetCount();
};
