// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartGridNavigator wrapper class

class CChartGridNavigator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartGridNavigator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa03df0b9, 0x4013, 0x48f9, { 0x9b, 0x1, 0x56, 0x88, 0x8e, 0xc1, 0x17, 0x76 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetGrid(LPDISPATCH newValue);
	void SetGridLink(long nNewValue);
	void EnableButtons();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
};
