// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPageControl;

/////////////////////////////////////////////////////////////////////////////
// CChartEditorPanel wrapper class

class CChartEditorPanel : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartEditorPanel)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x13e80fa9, 0xeb06, 0x4bfc, { 0x91, 0xb5, 0x62, 0xe, 0xb7, 0xbe, 0xf4, 0xcd } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void SelectUnderMouse();
	long GetBevelOuter();
	void SetBevelOuter(long nNewValue);
	void SetEditor(LPDISPATCH newValue);
	void SetEditorLink(long nNewValue);
	CPageControl GetMainPage();
	CPageControl GetSubPage();
};
