// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCrossTabSource wrapper class

class CCrossTabSource : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCrossTabSource)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x11a3fb6d, 0x915, 0x4be0, { 0x94, 0x1d, 0x64, 0x77, 0xfe, 0x8c, 0x39, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void Open();
	void Close();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	void Load();
	BOOL GetCaseSensitive();
	void SetCaseSensitive(BOOL bNewValue);
	VARIANT GetDataSet();
	void SetDataSet(const VARIANT& newValue);
	long GetFormula();
	void SetFormula(long nNewValue);
	CString GetGroupField();
	void SetGroupField(LPCTSTR lpszNewValue);
	CString GetLabelField();
	void SetLabelField(LPCTSTR lpszNewValue);
	CString GetValueField();
	void SetValueField(LPCTSTR lpszNewValue);
	BOOL GetHideSeries();
	void SetHideSeries(BOOL bNewValue);
};
