// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDragPointTool wrapper class

class CDragPointTool : public COleDispatchDriver
{
public:
	CDragPointTool() {}		// Calls COleDispatchDriver default constructor
	CDragPointTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDragPointTool(const CDragPointTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	long GetDragStyle();
	void SetDragStyle(long nNewValue);
};
