// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEnvironment wrapper class

class CEnvironment : public COleDispatchDriver
{
public:
	CEnvironment() {}		// Calls COleDispatchDriver default constructor
	CEnvironment(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEnvironment(const CEnvironment& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetNoPromptDBConnect();
	void SetNoPromptDBConnect(BOOL bNewValue);
	BOOL GetIEPrintWithPage();
	void SetIEPrintWithPage(BOOL bNewValue);
	void InternalRepaint();
	BOOL GetMouseWheelScroll();
	void SetMouseWheelScroll(BOOL bNewValue);
	CString GetDecimalSeparator();
	BOOL GetTeeClipWhenPrinting();
	void SetTeeClipWhenPrinting(BOOL bNewValue);
	BOOL GetTeeClipWhenMetafiling();
	void SetTeeClipWhenMetafiling(BOOL bNewValue);
	CString DecodeUTF8String(LPCTSTR AString);
	CString CodeUTF8String(LPCTSTR AString, BOOL addPrefix);
	BOOL GetChartVisible();
	void SetChartVisible(BOOL bNewValue);
};
