// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEPSExport wrapper class

class CEPSExport : public COleDispatchDriver
{
public:
	CEPSExport() {}		// Calls COleDispatchDriver default constructor
	CEPSExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEPSExport(const CEPSExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
};
