// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFaderTool wrapper class

class CFaderTool : public COleDispatchDriver
{
public:
	CFaderTool() {}		// Calls COleDispatchDriver default constructor
	CFaderTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFaderTool(const CFaderTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Start();
	void Stop();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetInitialDelay();
	void SetInitialDelay(long nNewValue);
	double GetSpeed();
	void SetSpeed(double newValue);
	long GetStyle();
	void SetStyle(long nNewValue);
};
