// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CFibonacciItem wrapper class

class CFibonacciItem : public COleDispatchDriver
{
public:
	CFibonacciItem() {}		// Calls COleDispatchDriver default constructor
	CFibonacciItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFibonacciItem(const CFibonacciItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetPen();
	double GetValue();
	void SetValue(double newValue);
};
