// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFullScreenTool wrapper class

class CFullScreenTool : public COleDispatchDriver
{
public:
	CFullScreenTool() {}		// Calls COleDispatchDriver default constructor
	CFullScreenTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFullScreenTool(const CFullScreenTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetReleaseKey();
	void SetReleaseKey(long nNewValue);
};
