// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGanttSeries;

/////////////////////////////////////////////////////////////////////////////
// CGanttTool wrapper class

class CGanttTool : public COleDispatchDriver
{
public:
	CGanttTool() {}		// Calls COleDispatchDriver default constructor
	CGanttTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGanttTool(const CGanttTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	BOOL GetAllowDrag();
	void SetAllowDrag(BOOL bNewValue);
	BOOL GetAllowResize();
	void SetAllowResize(BOOL bNewValue);
	short GetCursorDrag();
	void SetCursorDrag(short nNewValue);
	short GetCursorResize();
	void SetCursorResize(short nNewValue);
	long GetMinPixels();
	void SetMinPixels(long nNewValue);
	CGanttSeries GetGantt();
};
