// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGLPosition wrapper class

class CGLPosition : public COleDispatchDriver
{
public:
	CGLPosition() {}		// Calls COleDispatchDriver default constructor
	CGLPosition(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGLPosition(const CGLPosition& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetX();
	void SetX(double newValue);
	double GetY();
	void SetY(double newValue);
	double GetZ();
	void SetZ(double newValue);
};
