// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CJPEGExport wrapper class

class CJPEGExport : public COleDispatchDriver
{
public:
	CJPEGExport() {}		// Calls COleDispatchDriver default constructor
	CJPEGExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CJPEGExport(const CJPEGExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	BOOL GetGrayScale();
	void SetGrayScale(BOOL bNewValue);
	long GetCompressionQuality();
	void SetCompressionQuality(long nNewValue);
};
