// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShape;
class CTeeRect;
class CFramedBorder;
class CGaugePointerRange;
class CGaugeSeriesPointer;
class CPointer;
class CLinearGauge;
class CNumericGauge;
class CAxis;
class CCircularFrame;
class CGaugeHand;
class CTeePoint2D;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CKnobGauge wrapper class

class CKnobGauge : public COleDispatchDriver
{
public:
	CKnobGauge() {}		// Calls COleDispatchDriver default constructor
	CKnobGauge(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKnobGauge(const CKnobGauge& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CTeeShape GetFace();
	double GetValue();
	void SetValue(double newValue);
	CTeeRect GetCustomBounds();
	unsigned long GetPaletteColor(long Index);
	void SetCustomBounds(long ALeft, long ATop, long ARight, long ABottom);
	CFramedBorder GetFrame();
	CGaugePointerRange GetGreenLine();
	BOOL GetHorizontal();
	void SetHorizontal(BOOL bNewValue);
	double GetMaximum();
	void SetMaximum(double newValue);
	double GetMinimum();
	void SetMinimum(double newValue);
	long GetMinorTickDistance();
	void SetMinorTickDistance(long nNewValue);
	CGaugeSeriesPointer GetMinorTicks();
	CGaugePointerRange GetRedLine();
	CGaugeSeriesPointer GetTicks();
	CGaugeSeriesPointer GetCenter();
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	CPointer GetEndPoint();
	BOOL GetLabelsInside();
	void SetLabelsInside(BOOL bNewValue);
	BOOL GetRotateLabels();
	void SetRotateLabels(BOOL bNewValue);
	double GetRotationAngle();
	void SetRotationAngle(double newValue);
	double GetTotalAngle();
	void SetTotalAngle(double newValue);
	BOOL GetAutoPositionLinearGauge();
	void SetAutoPositionLinearGauge(BOOL bNewValue);
	BOOL GetAutoValueLinearGauge();
	void SetAutoValueLinearGauge(BOOL bNewValue);
	BOOL GetAutoPositionNumericGauge();
	void SetAutoPositionNumericGauge(BOOL bNewValue);
	BOOL GetAutoValueNumericGauge();
	void SetAutoValueNumericGauge(BOOL bNewValue);
	long GetDisplayTotalAngle();
	void SetDisplayTotalAngle(long nNewValue);
	long GetDisplayRotationAngle();
	void SetDisplayRotationAngle(long nNewValue);
	BOOL GetFillToSemiCircle();
	void SetFillToSemiCircle(BOOL bNewValue);
	long GetHandOffset();
	void SetHandOffset(long nNewValue);
	CLinearGauge GetLinearGauge();
	CNumericGauge GetNumericGauge();
	CAxis GetAxis();
	BOOL GetUseAxis();
	long GetCircleXCenter();
	long GetCircleYCenter();
	long GetXRadius();
	long GetYRadius();
	CCircularFrame GetCircularFrame();
	CGaugeHand GetHand();
	CTeePoint2D GetCenterPoint();
	CGradient GetHighLight();
	BOOL GetActiveCenter();
	void SetActiveCenter(BOOL bNewValue);
	BOOL GetAxisInside();
	void SetAxisInside(BOOL bNewValue);
};
