// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLightFilter wrapper class

class CLightFilter : public COleDispatchDriver
{
public:
	CLightFilter() {}		// Calls COleDispatchDriver default constructor
	CLightFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLightFilter(const CLightFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFactor();
	void SetFactor(long nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
};
