// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CLinePointSeries wrapper class

class CLinePointSeries : public COleDispatchDriver
{
public:
	CLinePointSeries() {}		// Calls COleDispatchDriver default constructor
	CLinePointSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLinePointSeries(const CLinePointSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	BOOL GetFastPoint();
	void SetFastPoint(BOOL bNewValue);
	long GetTreatNulls();
	void SetTreatNulls(long nNewValue);
	CPen1 GetLinesPen();
};
