// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CMoneyFlowFunction wrapper class

class CMoneyFlowFunction : public COleDispatchDriver
{
public:
	CMoneyFlowFunction() {}		// Calls COleDispatchDriver default constructor
	CMoneyFlowFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoneyFlowFunction(const CMoneyFlowFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAccumulate();
	void SetAccumulate(BOOL bNewValue);
	VARIANT GetVolume();
	void SetVolume(const VARIANT& newValue);
	CPen1 GetHistogramPen();
	CPen1 GetAreaPen();
	long GetCMFStyle();
	void SetCMFStyle(long nNewValue);
	unsigned long GetUpColor();
	void SetUpColor(unsigned long newValue);
	unsigned long GetDownColor();
	void SetDownColor(unsigned long newValue);
};
