// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CNearestTool wrapper class

class CNearestTool : public COleDispatchDriver
{
public:
	CNearestTool() {}		// Calls COleDispatchDriver default constructor
	CNearestTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CNearestTool(const CNearestTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	CBrush1 GetBrush();
	BOOL GetDrawLine();
	void SetDrawLine(BOOL bNewValue);
	BOOL GetFullRepaint();
	void SetFullRepaint(BOOL bNewValue);
	CPen1 GetPen();
	long GetSize();
	void SetSize(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetPoint();
	void SetPoint(long nNewValue);
};
