#if !defined(AFX_PAGECONTROL_H__24E4FB72_21E2_4C62_9AC0_CE665E455419__INCLUDED_)
#define AFX_PAGECONTROL_H__24E4FB72_21E2_4C62_9AC0_CE665E455419__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPageControl wrapper class

class CPageControl : public COleDispatchDriver
{
public:
	CPageControl() {}		// Calls COleDispatchDriver default constructor
	CPageControl(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPageControl(const CPageControl& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetTabPosition();
	void SetTabPosition(long nNewValue);
	long GetTabStyle();
	void SetTabStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PAGECONTROL_H__24E4FB72_21E2_4C62_9AC0_CE665E455419__INCLUDED_)
