// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CPieTool wrapper class

class CPieTool : public COleDispatchDriver
{
public:
	CPieTool() {}		// Calls COleDispatchDriver default constructor
	CPieTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieTool(const CPieTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	CPen1 GetPen();
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetSlice();
};
