// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CSelectorTool wrapper class

class CSelectorTool : public COleDispatchDriver
{
public:
	CSelectorTool() {}		// Calls COleDispatchDriver default constructor
	CSelectorTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSelectorTool(const CSelectorTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAllowDrag();
	void SetAllowDrag(BOOL bNewValue);
	BOOL GetAllowResizeChart();
	void SetAllowResizeChart(BOOL bNewValue);
	CBrush1 GetBrush();
	long GetHandleSize();
	void SetHandleSize(long nNewValue);
	CPen1 GetPen();
};
