// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSeriesTextField wrapper class

class CSeriesTextField : public COleDispatchDriver
{
public:
	CSeriesTextField() {}		// Calls COleDispatchDriver default constructor
	CSeriesTextField(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeriesTextField(const CSeriesTextField& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFieldIndex();
	void SetFieldIndex(long nNewValue);
	CString GetFieldName();
	void SetFieldName(LPCTSTR lpszNewValue);
};
