// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeriesTextField;

/////////////////////////////////////////////////////////////////////////////
// CSeriesTextFields wrapper class

class CSeriesTextFields : public COleDispatchDriver
{
public:
	CSeriesTextFields() {}		// Calls COleDispatchDriver default constructor
	CSeriesTextFields(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeriesTextFields(const CSeriesTextFields& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSeriesTextField GetItems(long Index);
	void Clear();
	void Delete(long Index);
	long GetCount();
};
