// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeriesTextFields;
class CSeriesTextField;

/////////////////////////////////////////////////////////////////////////////
// CSeriesTextSource wrapper class

class CSeriesTextSource : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSeriesTextSource)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x982ac727, 0x6a12, 0x43c6, { 0xae, 0x40, 0x9, 0xd3, 0x3f, 0xe4, 0xd6, 0x4f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void Open();
	void Close();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	void Load();
	void LoadFromFile(LPCTSTR FileName);
	void LoadFromURL(LPCTSTR URL);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	long GetLoadMode();
	void SetLoadMode(long nNewValue);
	void LoadAsStream(const VARIANT& AStream);
	long GetHeaderLines();
	void SetHeaderLines(long nNewValue);
	CSeriesTextFields GetFields();
	CString GetFieldSeparator();
	void SetFieldSeparator(LPCTSTR lpszNewValue);
	CSeriesTextField AddField(LPCTSTR AName, long AIndex);
	void LoadFromStrings(LPCTSTR AStrings);
};
