// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSkewnessFunction wrapper class

class CSkewnessFunction : public COleDispatchDriver
{
public:
	CSkewnessFunction() {}		// Calls COleDispatchDriver default constructor
	CSkewnessFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSkewnessFunction(const CSkewnessFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetComplete();
	void SetComplete(BOOL bNewValue);
};
