// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSubChartChart;

/////////////////////////////////////////////////////////////////////////////
// CSubChart wrapper class

class CSubChart : public COleDispatchDriver
{
public:
	CSubChart() {}		// Calls COleDispatchDriver default constructor
	CSubChart(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSubChart(const CSubChart& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAllowDrag();
	void SetAllowDrag(BOOL bNewValue);
	BOOL GetAllowResize();
	void SetAllowResize(BOOL bNewValue);
	CSubChartChart GetChart();
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
};
