// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartCollection;

/////////////////////////////////////////////////////////////////////////////
// CSubChartTool wrapper class

class CSubChartTool : public COleDispatchDriver
{
public:
	CSubChartTool() {}		// Calls COleDispatchDriver default constructor
	CSubChartTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSubChartTool(const CSubChartTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CChartCollection GetCharts();
	short GetCursor();
	void SetCursor(short nNewValue);
};
