// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSVGExport wrapper class

class CSVGExport : public COleDispatchDriver
{
public:
	CSVGExport() {}		// Calls COleDispatchDriver default constructor
	CSVGExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSVGExport(const CSVGExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
};
