// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeCommanderButton;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CTeeCommander wrapper class

class CTeeCommander : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeCommander)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x34ce48ee, 0x8287, 0x4af4, { 0xa2, 0x8e, 0xa1, 0x2c, 0xa6, 0x59, 0x71, 0x7 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	BOOL GetLabelValues();
	void SetLabelValues(BOOL bNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void SetEditor(LPDISPATCH newValue);
	void SetPreviewer(LPDISPATCH newValue);
	void SetEditorLink(long nNewValue);
	void SetPreviewerLink(long nNewValue);
	BOOL GetVertical();
	void SetVertical(BOOL bNewValue);
	VARIANT GetControls();
	void SetControls(const VARIANT& newValue);
	VARIANT GetButtons();
	void SetButtons(const VARIANT& newValue);
	long GetBevelInner();
	void SetBevelInner(long nNewValue);
	long GetBevelOuter();
	void SetBevelOuter(long nNewValue);
	long GetBevelWidth();
	void SetBevelWidth(long nNewValue);
	long GetBevelOffset();
	void SetBevelOffset(long nNewValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	long GetDefaultButton();
	void SetDefaultButton(long nNewValue);
	CTeeCommanderButton GetButton3D();
	CTeeCommanderButton GetButtonCopy();
	CTeeCommanderButton GetButtonDepth();
	CTeeCommanderButton GetButtonEdit();
	CTeeCommanderButton GetButtonMove();
	CTeeCommanderButton GetButtonNormal();
	CTeeCommanderButton GetButtonPrint();
	CTeeCommanderButton GetButtonRotate();
	CTeeCommanderButton GetButtonSave();
	CTeeCommanderButton GetButtonZoom();
	void RepositionControls();
	CGradient GetGradient();
	BOOL GetFullRotation();
	void SetFullRotation(BOOL bNewValue);
	long GetRotateInertia();
	void SetRotateInertia(long nNewValue);
};
