// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeCommanderButton wrapper class

class CTeeCommanderButton : public COleDispatchDriver
{
public:
	CTeeCommanderButton() {}		// Calls COleDispatchDriver default constructor
	CTeeCommanderButton(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeCommanderButton(const CTeeCommanderButton& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Hide();
};
