// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeEditorShowPages wrapper class

class CTeeEditorShowPages : public COleDispatchDriver
{
public:
	CTeeEditorShowPages() {}		// Calls COleDispatchDriver default constructor
	CTeeEditorShowPages(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeEditorShowPages(const CTeeEditorShowPages& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetMain();
	void SetMain(BOOL bNewValue);
	BOOL GetGeneral();
	void SetGeneral(BOOL bNewValue);
	BOOL GetAxis();
	void SetAxis(BOOL bNewValue);
	BOOL GetTitles();
	void SetTitles(BOOL bNewValue);
	BOOL GetLegend();
	void SetLegend(BOOL bNewValue);
	BOOL GetPanel();
	void SetPanel(BOOL bNewValue);
	BOOL GetPaging();
	void SetPaging(BOOL bNewValue);
	BOOL GetWalls();
	void SetWalls(BOOL bNewValue);
	BOOL GetAspect();
	void SetAspect(BOOL bNewValue);
	BOOL GetSeriesGeneral();
	void SetSeriesGeneral(BOOL bNewValue);
	BOOL GetSeriesMarks();
	void SetSeriesMarks(BOOL bNewValue);
	BOOL GetTools();
	void SetTools(BOOL bNewValue);
	BOOL GetSeriesData();
	void SetSeriesData(BOOL bNewValue);
	BOOL GetExportDialog();
	void SetExportDialog(BOOL bNewValue);
	BOOL GetPrintPreview();
	void SetPrintPreview(BOOL bNewValue);
	BOOL GetOpenGL();
	void SetOpenGL(BOOL bNewValue);
	void SetThemes(BOOL bNewValue);
	BOOL GetExportNative();
	void SetExportNative(BOOL bNewValue);
	BOOL GetAllSeries();
	void SetAllSeries(BOOL bNewValue);
};
