// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeEditorShowPages;
class CTeeEditorOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeeEditor wrapper class

class CTeeEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8ec37834, 0x7116, 0x424b, { 0x97, 0x27, 0xb, 0xd3, 0xa, 0xb4, 0x51, 0x41 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	CString GetEditorTitle();
	void SetEditorTitle(LPCTSTR lpszNewValue);
	long GetDefaultPage();
	void SetDefaultPage(long nNewValue);
	void ShowEditor();
	BOOL GetAutoRepaint();
	void SetAutoRepaint(BOOL bNewValue);
	CTeeEditorShowPages GetShowPages();
	long GetEditorLink();
	CTeeEditorOptions GetOptions();
	BOOL GetTreeView();
	void SetTreeView(BOOL bNewValue);
	BOOL GetHighLightTabs();
	void SetHighLightTabs(BOOL bNewValue);
	long GetPixelsPerInch();
	void SetPixelsPerInch(long nNewValue);
	BOOL GetRememberPosition();
	void SetRememberPosition(BOOL bNewValue);
	long GetGalleryHeight();
	void SetGalleryHeight(long nNewValue);
	long GetGalleryWidth();
	void SetGalleryWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
};
