// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeGDIPlus wrapper class

class CTeeGDIPlus : public COleDispatchDriver
{
public:
	CTeeGDIPlus() {}		// Calls COleDispatchDriver default constructor
	CTeeGDIPlus(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeGDIPlus(const CTeeGDIPlus& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	BOOL GetAntialias();
	void SetAntialias(BOOL bNewValue);
	BOOL GetAntiAliasText();
	void SetAntiAliasText(BOOL bNewValue);
};
