// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePreviewerOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeePreviewer wrapper class

class CTeePreviewer : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeePreviewer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd436cc3d, 0x299f, 0x45b9, { 0x99, 0xfa, 0x9, 0x4d, 0x55, 0x5, 0x2d, 0xba } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	CString GetPreviewTitle();
	void SetPreviewTitle(LPCTSTR lpszNewValue);
	void ShowPreview();
	unsigned long GetPaperColor();
	void SetPaperColor(unsigned long newValue);
	long GetPreviewerLink();
	BOOL GetMaximized();
	void SetMaximized(BOOL bNewValue);
	CTeePreviewerOptions GetOptions();
};
