#if !defined(AFX_TEEPANNING_H__674DE433_EA73_42D2_B283_020C78FD01B8__INCLUDED_)
#define AFX_TEEPANNING_H__674DE433_EA73_42D2_B283_020C78FD01B8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeePanning wrapper class

class CTeePanning : public COleDispatchDriver
{
public:
	CTeePanning() {}		// Calls COleDispatchDriver default constructor
	CTeePanning(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeePanning(const CTeePanning& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetInsideBounds();
	void SetInsideBounds(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEPANNING_H__674DE433_EA73_42D2_B283_020C78FD01B8__INCLUDED_)
