// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CBrush1;
class CPen1;
class CGradient;
class CTeePoint2D;
class CPointer;

/////////////////////////////////////////////////////////////////////////////
// CTernarySeries wrapper class

class CTernarySeries : public COleDispatchDriver
{
public:
	CTernarySeries() {}		// Calls COleDispatchDriver default constructor
	CTernarySeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTernarySeries(const CTernarySeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddXYZ(double AX, double AY, double AZ, LPCTSTR AXLabel, unsigned long Value);
	double MaxZValue();
	double MinZValue();
	long GetTimesZOrder();
	void SetTimesZOrder(long nNewValue);
	CValueList GetZValues();
	double GetZValue(long Index);
	void SetZValue(long Index, double newValue);
	CBrush1 GetBrush();
	CPen1 GetPen();
	void AddArrayXYZ(const VARIANT& XArray, const VARIANT& YArray, const VARIANT& ZArray);
	void AddArrayGrid(long NumX, long NumZ, const VARIANT& XZArray);
	long CalcZPos(long ValueIndex);
	long AddPalette(double Value, unsigned long Color);
	unsigned long GetStartColor();
	void SetStartColor(unsigned long newValue);
	unsigned long GetEndColor();
	void SetEndColor(unsigned long newValue);
	long GetPaletteSteps();
	void SetPaletteSteps(long nNewValue);
	BOOL GetUsePalette();
	void SetUsePalette(BOOL bNewValue);
	BOOL GetUseColorRange();
	void SetUseColorRange(BOOL bNewValue);
	void ClearPalette();
	void CreateDefaultPalette(long NumSteps);
	unsigned long GetSurfacePaletteColor(double Y);
	unsigned long GetMidColor();
	void SetMidColor(unsigned long newValue);
	void CreateRangePalette();
	long GetPaletteStyle();
	void SetPaletteStyle(long nNewValue);
	BOOL GetUsePaletteMin();
	void SetUsePaletteMin(BOOL bNewValue);
	double GetPaletteMin();
	void SetPaletteMin(double newValue);
	double GetPaletteStep();
	void SetPaletteStep(double newValue);
	void InvertPalette();
	void AddCustomPalette(const VARIANT& colorArray);
	CValueList GetRadiusValues();
	CValueList GetWeightValues();
	CGradient GetGradient();
	CPen1 GetLinesPen();
	BOOL GetRotateLabels();
	void SetRotateLabels(BOOL bNewValue);
	long GetTernaryStyle();
	void SetTernaryStyle(long nNewValue);
	long GetTernaryLegendStyle();
	void SetTernaryLegendStyle(long nNewValue);
	long GetTernaryMarkStyle();
	void SetTernaryMarkStyle(long nNewValue);
	long GetAxisScale();
	void SetAxisScale(long nNewValue);
	CTeePoint2D GetVertexA();
	CTeePoint2D GetVertexB();
	CTeePoint2D GetVertexC();
	CPointer GetPointer();
	long AddBubbleXYZ(double AX, double AY, double AZ, double ARadius, LPCTSTR ALabel, unsigned long AColor);
	long AddBubbleXYZWeight(double AX, double AY, double AZ, double ARadius, double AWeight, LPCTSTR ALabel, unsigned long AColor);
	LPDISPATCH CalcPointFromValues(double a, double b, double C);
};
