// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCursorTool;
class CDragMarksTool;
class CAxisArrowTool;
class CDrawLineTool;
class CNearestTool;
class CColorBandTool;
class CColorLineTool;
class CRotateTool;
class CMarksTipTool;
class CChartImageTool;
class CAnnotationTool;
class CPageNumTool;
class CGridTransposeTool;
class CExtraLegendTool;
class CSeriesAnimationTool;
class CGanttTool;
class CGridBandTool;
class CPieTool;
class CDragPointTool;
class CLegendScrollBarTool;
class CLightTool;
class CSurfaceNearestTool;
class CAxisScrollTool;
class CSeriesBandTool;
class CSelectorTool;
class CRectangleTool;
class CDataTableTool;
class CVideoTool;
class CVideoPlayerTool;
class CTransposeSeriesTool;
class CSeriesRegionTool;
class CAntiAliasTool;
class CClipSeriesTool;
class CFaderTool;
class CFrameTool;
class CMagnifyTool;
class CLegendPaletteTool;
class CBannerTool;
class CText3DTool;
class CSeriesStatsTool;
class CLinkTool;
class CFibonacciTool;
class CFullScreenTool;
class CAxisBreaksTool;
class CSubChartTool;

/////////////////////////////////////////////////////////////////////////////
// CTools wrapper class

class CTools : public COleDispatchDriver
{
public:
	CTools() {}		// Calls COleDispatchDriver default constructor
	CTools(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTools(const CTools& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CCursorTool GetAsTeeCursor();
	CDragMarksTool GetAsDragMarks();
	CAxisArrowTool GetAsAxisArrow();
	CDrawLineTool GetAsDrawLine();
	CNearestTool GetAsNearest();
	CColorBandTool GetAsColorband();
	CColorLineTool GetAsColorLine();
	CRotateTool GetAsRotate();
	CMarksTipTool GetAsMarksTip();
	CChartImageTool GetAsChartImage();
	CAnnotationTool GetAsAnnotation();
	CPageNumTool GetAsPageNum();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	CString GetDescription();
	long GetToolType();
	void ShowEditor();
	CGridTransposeTool GetAsGridTranspose();
	CExtraLegendTool GetAsExtraLegend();
	CSeriesAnimationTool GetAsSeriesAnimation();
	CGanttTool GetAsGantt();
	CGridBandTool GetAsGridBand();
	CPieTool GetAsPie();
	CDragPointTool GetAsDragPoint();
	CLegendScrollBarTool GetAsLegendScrollBar();
	CLightTool GetAsLight();
	CSurfaceNearestTool GetAsSurfaceNearest();
	CAxisScrollTool GetAsAxisScroll();
	CSeriesBandTool GetAsSeriesBand();
	CSelectorTool GetAsSelector();
	CRectangleTool GetAsRectangle();
	BOOL GetShowInEditor();
	void SetShowInEditor(BOOL bNewValue);
	CDataTableTool GetAsDataTable();
	CVideoTool GetAsVideo();
	CVideoPlayerTool GetAsVideoPlayer();
	CTransposeSeriesTool GetAsTransposeSeries();
	CSeriesRegionTool GetAsSeriesRegion();
	CAntiAliasTool GetAsAntiAlias();
	CClipSeriesTool GetAsClipSeries();
	CFaderTool GetAsFader();
	CFrameTool GetAsFrame();
	CMagnifyTool GetAsMagnify();
	CLegendPaletteTool GetAsLegendPalette();
	CBannerTool GetAsBanner();
	CText3DTool GetAsText3D();
	CSeriesStatsTool GetAsSeriesStats();
	CLinkTool GetAsLink();
	CFibonacciTool GetAsFibonacci();
	CFullScreenTool GetAsFullScreen();
	CAxisBreaksTool GetAsAxisBreaks();
	CSubChartTool GetAsSubChart();
};
