// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTransposeSeriesTool wrapper class

class CTransposeSeriesTool : public COleDispatchDriver
{
public:
	CTransposeSeriesTool() {}		// Calls COleDispatchDriver default constructor
	CTransposeSeriesTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTransposeSeriesTool(const CTransposeSeriesTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Transpose();
};
