// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COrgItem;
class COrgShape;
class COrgItemCollection;
class CSpacing;

/////////////////////////////////////////////////////////////////////////////
// CTreeMapSeries wrapper class

class CTreeMapSeries : public COleDispatchDriver
{
public:
	CTreeMapSeries() {}		// Calls COleDispatchDriver default constructor
	CTreeMapSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTreeMapSeries(const CTreeMapSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add(LPCTSTR Text, long Superior);
	long FirstChild(long ValueIndex);
	// method 'GetBounds' not emitted because of invalid return type or parameter type
	COrgItem GetItem(long Index);
	COrgShape GetFormat();
	COrgItemCollection GetItems();
	long GetLineStyle();
	void SetLineStyle(long nNewValue);
	CSpacing GetSpacing();
	long GetMapStyle();
	void SetMapStyle(long nNewValue);
	long GetPaletteSteps();
	void SetPaletteSteps(long nNewValue);
	double GetValue(long Index);
	void SetValue(long Index, double newValue);
	long AddValue(double AValue, LPCTSTR ALabel, long ASuperior, unsigned long AColor);
};
