// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVideoTool wrapper class

class CVideoTool : public COleDispatchDriver
{
public:
	CVideoTool() {}		// Calls COleDispatchDriver default constructor
	CVideoTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoTool(const CVideoTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void StartRecording(LPCTSTR FileName);
	void StopRecording();
	long GetFrameCount();
	BOOL GetIsRecording();
	CString GetCompression();
	void SetCompression(LPCTSTR lpszNewValue);
	long GetCompressionQuality();
	void SetCompressionQuality(long nNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	long GetFrameDuration();
	void SetFrameDuration(long nNewValue);
};
