// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePicture;
class CFilterItems;

/////////////////////////////////////////////////////////////////////////////
// CVideoPlayerTool wrapper class

class CVideoPlayerTool : public COleDispatchDriver
{
public:
	CVideoPlayerTool() {}		// Calls COleDispatchDriver default constructor
	CVideoPlayerTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoPlayerTool(const CVideoPlayerTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetPaused();
	CTeePicture GetImage();
	BOOL GetPlaying();
	long GetPosition();
	void SetPosition(long nNewValue);
	long GetStartFrame();
	long GetEndFrame();
	long GetDelay();
	void SetDelay(long nNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	CFilterItems GetFilters();
	void Pause();
	void Play();
	void Stop();
};
