// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CXAMLExport wrapper class

class CXAMLExport : public COleDispatchDriver
{
public:
	CXAMLExport() {}		// Calls COleDispatchDriver default constructor
	CXAMLExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CXAMLExport(const CXAMLExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
};
